### ISSUE TITLE
Alarms and timers crashing on Android 7.0

### ISSUE THREAD

**Issue by philliphsu** [philliphsu/ClockPlus#8]
Affected classes:
- UpcomingAlarmReceiver
- RingtoneActivity
  - AlarmActivity
  - TimesUpActivity

**Comment by Bluesir9** [comment]
@philliphsu Hey, mind if I give this a shot?

**Comment by philliphsu** [comment]
Feel free to send a pull request.

**Comment by Bluesir9** [comment]
@philliphsu A small update. Looks like API 24 does not support usage of Parcelable object in AlarmManager, as specified [here](http://stackoverflow.com/questions/38466080/dp5-7-0-does-adding-extras-to-a-pending-intent-fail) which is the reason behind the crashes in Android Nougat. Not sure if you already know about this but i just thought it would be good to put this out here.

**Comment by philliphsu** [comment]
Haven't had the time to investigate, so thanks for pointing this out! I'll look into the solution provided in the link in further detail.

**Comment by haayhappen** [comment]
Hey @philliphsu and @Bluesir9 ,
is anyone of you still on this? 
Need to get the upcomingAlarmReceiver working on Android 7 and didn't have success yet.

**Comment by haayhappen** [comment]
actually I think this would do the trick: [marshall-and-unmarshall-a-parcelable](http://stackoverflow.com/questions/18000093/how-to-marshall-and-unmarshall-a-parcelable-to-a-byte-array-with-help-of-parcel/18000094#18000094)

**Comment by haayhappen** [comment]
Just in case you want to save you some time on this: I fixed it.
Make a class ParcelableUtil like shown in the above link. 
In every Pending request you send, hand over the alarm as a bytearray instead of an alarm. 
Later use this to unmarshall it:  
//get extras bundle from pending intent
        Bundle extras = intent.getExtras();
        //get the byte array out of the intents' extras
        byte[] byteArray = extras.getByteArray(EXTRA_ALARM);
        //unmarshall the array to our parcel(alarm)
        final Alarm alarm = ParcelableUtil.unmarshall(byteArray,Alarm.CREATOR);

**Comment by Bluesir9** [comment]
@haayhappen Haven't gotten around working on this nearly enough so you are free to pick it up. Sorry for taking so much time to respond.

**Comment by philliphsu** [comment]
I was finally able to fix the problem. Alarms and timers should be working on Nougat now. Thanks @haayhappen

**Comment by philliphsu** [comment]
Reopening because I am getting reports that people on 7.0+ are still experiencing crashes.
